# Site settings
title: rook.io
url: "http://rook.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-93639004-1

# Build settings
markdown: kramdown

# plugins
# NOTE: github pages ignores custom plugins and any other plugin which is not whitelisted
# SEE: https://pages.github.com/versions/
gems:
  - jekyll-relative-links
  - jekyll-babel
  - jekyll-readme-index

exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "docs/rook"
    values:
      layout: "docs"
      github: "https://github.com/rook/rook/blob/"
      docsRoot: "/Documentation"
